/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import DB.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Himal
 */
public class ViewToBeReturnedBooks extends javax.swing.JFrame {
    //declaring instance variables
    Connection connection;
    Statement statement;
    ResultSet rsltSet;

    boolean haveBooks = false;
    int NoOfBooks = 0;
    Object bookDetails[][];

    /**
     * Creates new form SearchBook
     */
    public ViewToBeReturnedBooks() {
        initComponents();

        //initializes the connection to database
        connection = DBConnection.getDBConnection().getConnection();

        //views all to be returned books when the window opens
        jBtnViewAll.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTxtSearch = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnBack = new javax.swing.JButton();
        jRadioButtonStudentID = new javax.swing.JRadioButton();
        jRadioButtonBookID = new javax.swing.JRadioButton();
        jBtnViewAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View To Be Retuned Books");
        setResizable(false);

        jTxtSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBtnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSearchMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Book ID", "Title", "Author", "Student ID", "Name", "Admission Number", "Faculty", "Year", "Issued Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(90);
        }

        jBtnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jBtnBack.setText("Back");
        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
        });
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStudentID);
        jRadioButtonStudentID.setText("Search by Student ID");

        buttonGroup1.add(jRadioButtonBookID);
        jRadioButtonBookID.setSelected(true);
        jRadioButtonBookID.setText("Search by Book ID");

        jBtnViewAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnViewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view_all.png"))); // NOI18N
        jBtnViewAll.setText("View All");
        jBtnViewAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnViewAllMouseClicked(evt);
            }
        });
        jBtnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonStudentID))
                            .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jBtnViewAll, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonStudentID)
                    .addComponent(jRadioButtonBookID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        this.dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSearchMouseClicked
        NoOfBooks = 0;
        haveBooks = false;

        if (jRadioButtonBookID.isSelected()) {

            if (!jTxtSearch.getText().equals("")) {
               //checks whether the input for the bookID is a number
                try {
                    int x = Integer.parseInt(jTxtSearch.getText());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Enter a valid number for book ID");
                    return;
                }

                int searchBookID = Integer.parseInt(jTxtSearch.getText());

                //searches the database for given bookID
                try {
                    searchByBookID(searchBookID);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

                if (haveBooks) {
                    loadToTable(bookDetails);
                } else {
                    DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                    table.setNumRows(0);
                    JOptionPane.showMessageDialog(null, "No books found by given Book ID");
                }
            } else if (jTxtSearch.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter the Book ID");
            }
        }

        if (jRadioButtonStudentID.isSelected()) {

            if (!jTxtSearch.getText().equals("")) {
                //checks whether the input for the studentID is a number
                try {
                    int y = Integer.parseInt(jTxtSearch.getText());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Enter a valid number for student ID");
                    return;
                }

                int searchStudentID = Integer.parseInt(jTxtSearch.getText());

                //searches the database for given studentID
                try {
                    searchByStudentID(searchStudentID);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

                if (haveBooks) {
                    loadToTable(bookDetails);
                    if (NoOfBooks == 1) {
                        JOptionPane.showMessageDialog(null, "1 book has to be returned by this student");
                    } else if (NoOfBooks > 1) {
                        JOptionPane.showMessageDialog(null, NoOfBooks + " books have to be returned by this student");
                    }
                } else {
                    DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                    table.setNumRows(0);
                    JOptionPane.showMessageDialog(null, "No books have to be returned by this student");
                }
            } else if (jTxtSearch.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter the Student ID");
            }
        }
    }//GEN-LAST:event_jBtnSearchMouseClicked

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        this.dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnViewAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnViewAllMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnViewAllMouseClicked

    private void jBtnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewAllActionPerformed
        NoOfBooks = 0;
        haveBooks = false;

        try {
            viewAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        if (haveBooks) {
            loadToTable(bookDetails);
        } else {
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setNumRows(0);
            JOptionPane.showMessageDialog(null, "No to be returned books found");
        }
    }//GEN-LAST:event_jBtnViewAllActionPerformed

    public Object[][] searchByBookID(int bookID) throws SQLException {
        //searches the issued_book table for given book ID
        try {
            String query = "SELECT * FROM issued_book WHERE Book_ID = " + "'" + bookID + "'";

            statement = connection.createStatement();
            rsltSet = statement.executeQuery(query);

            //if the result set is not empty
            if (rsltSet.next()) {
                haveBooks = true;

                //counts the number of books by given book ID
                rsltSet.beforeFirst();
                while (rsltSet.next()) {
                    NoOfBooks++;
                }

                //inserts details of all books in to arrays
                bookDetails = new Object[NoOfBooks][10];
                rsltSet.beforeFirst();
                for (int i = 0; i < NoOfBooks; i++) {
                    rsltSet.next();

                    bookDetails[i][0] = i + 1;
                    bookDetails[i][1] = rsltSet.getInt(1);
                    bookDetails[i][2] = rsltSet.getString(2);
                    bookDetails[i][3] = rsltSet.getString(3);
                    bookDetails[i][4] = rsltSet.getInt(7);
                    bookDetails[i][5] = rsltSet.getString(8);
                    bookDetails[i][6] = rsltSet.getString(9);
                    bookDetails[i][7] = rsltSet.getString(10);
                    bookDetails[i][8] = rsltSet.getInt(11);
                    bookDetails[i][9] = rsltSet.getDate(12);
                }

                statement.close();
                rsltSet.close();
            } else {
                haveBooks = false;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        return bookDetails;
    }

    public Object[][] searchByStudentID(int studentID) throws SQLException {
        //searches the issued_book table for given student ID
        try {
            String query = "SELECT * FROM issued_book WHERE Student_ID = " + "'" + studentID + "'";

            statement = connection.createStatement();
            rsltSet = statement.executeQuery(query);

            //if the result set is not empty
            if (rsltSet.next()) {
                haveBooks = true;

                //counts the number of books by given student ID
                rsltSet.beforeFirst();
                while (rsltSet.next()) {
                    NoOfBooks++;
                }

                //inserts details of all books in to arrays
                bookDetails = new Object[NoOfBooks][12];
                rsltSet.beforeFirst();
                for (int i = 0; i < NoOfBooks; i++) {
                    rsltSet.next();

                    bookDetails[i][0] = i + 1;
                    bookDetails[i][1] = rsltSet.getInt(1);
                    bookDetails[i][2] = rsltSet.getString(2);
                    bookDetails[i][3] = rsltSet.getString(3);
                    bookDetails[i][4] = rsltSet.getInt(7);
                    bookDetails[i][5] = rsltSet.getString(8);
                    bookDetails[i][6] = rsltSet.getString(9);
                    bookDetails[i][7] = rsltSet.getString(10);
                    bookDetails[i][8] = rsltSet.getInt(11);
                    bookDetails[i][9] = rsltSet.getDate(12);
                }

                statement.close();
                rsltSet.close();
            } else {
                haveBooks = false;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        return bookDetails;
    }

    public Object[][] viewAll() throws SQLException {
        //searches all books in the issued_book table
        try {
            String query = "SELECT * FROM issued_book";

            statement = connection.createStatement();
            rsltSet = statement.executeQuery(query);

            //if the result set is not empty
            if (rsltSet.next()) {
                haveBooks = true;

                //counts the number of books
                rsltSet.beforeFirst();
                while (rsltSet.next()) {
                    NoOfBooks++;
                }

                //inserts details of all books in to arrays
                bookDetails = new Object[NoOfBooks][12];
                rsltSet.beforeFirst();
                for (int i = 0; i < NoOfBooks; i++) {
                    rsltSet.next();

                    bookDetails[i][0] = i + 1;
                    bookDetails[i][1] = rsltSet.getInt(1);
                    bookDetails[i][2] = rsltSet.getString(2);
                    bookDetails[i][3] = rsltSet.getString(3);
                    bookDetails[i][4] = rsltSet.getInt(7);
                    bookDetails[i][5] = rsltSet.getString(8);
                    bookDetails[i][6] = rsltSet.getString(9);
                    bookDetails[i][7] = rsltSet.getString(10);
                    bookDetails[i][8] = rsltSet.getInt(11);
                    bookDetails[i][9] = rsltSet.getDate(12);
                }

                statement.close();
                rsltSet.close();
            } else {
                haveBooks = false;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        return bookDetails;
    }

    private void loadToTable(Object bookDetails[][]) {
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        table.setNumRows(0);

        for (int i = 0; i < NoOfBooks; i++) {
            Object[] row = {bookDetails[i][0], bookDetails[i][1], bookDetails[i][2], bookDetails[i][3], bookDetails[i][4], bookDetails[i][5], bookDetails[i][6], bookDetails[i][7], bookDetails[i][8], bookDetails[i][9]};

            table.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewToBeReturnedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewToBeReturnedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewToBeReturnedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewToBeReturnedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewToBeReturnedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnViewAll;
    private javax.swing.JRadioButton jRadioButtonBookID;
    private javax.swing.JRadioButton jRadioButtonStudentID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtSearch;
    // End of variables declaration//GEN-END:variables
}
